### ISSUE TITLE
Throw exception instead of silent fail

### ISSUE THREAD

**Issue by ydkhatri** [K0lb3/tex2img#3]
https://github.com/K0lb3/tex2img/blob/7b1aea9d9dd459db4366e9db3333675479ff1af0/src/main.cpp#L185

On the above referenced line, this would be better to throw an exception like `raise ValueError('Failed decoding')` instead of printf(). This helps anyone using the library in detecting errors. If you anticipate that users may need the script to still move on and continue processing, perhaps add a boolean argument to the function like `ignore_errors=False`

**Comment by K0lb3** [comment]
An exception would indeed be better, but the tex2img module is written in C and it isn't that easy to catch an unknown error in C and throw a suiting Python error.
I don't have enough time to research how to do so in a fail-safe way.
It would be great if someone could research that and make a PR.

**Comment by ydkhatri** [comment]
Yes, that is true. Basisu code may be faulty, as it leads to python seg fault and crash for me after printing out several 'failed decoding' messages. For what I needed I ended up using your astc_decomp project and that works without errors.
