### ISSUE TITLE
Crash on decompressing PVRTC_RGBA4 textures

### ISSUE THREAD

**Issue by larryhou** [K0lb3/tex2img#5]
`tex2img` is an awesome tool, it's working very well with common ETC(2) or ASTC textures, however it crashes on decompressing PVRTC_RGBA4 textures.

**Comment by K0lb3** [comment]
The tests confirm that the decompression of pvrtc rgb4 works.
Have you tried decompressing your texture with other tools?

**Comment by larryhou** [comment]
Sorry to bother you, it was wrong parameters which caused the crash.
